image: python:3.6.6-stretch

stages:
  - test
  - deploy

before_script:
    - echo "Start CI/CD"
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - python -m unittest discover tests

deploy:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y
    - apt-get install apt-transport-https ca-certificates gnupg -y
    - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    - apt-get update
    - apt-get install google-cloud-sdk -y
    - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT_FILE
    - virtualenv venv
    - pip install -r requirements.txt
    - gcloud app deploy app.yaml --quiet --project $GOOGLE_PROJECT_ID

after_script:
  - echo "End CI/CD"
